[WIP] Add initial support for IMX8
thesofproject/qemu pull request #28
Opened 2020-01-17 13:49 UTC by dianacretu

2020-01-17 14:41 UTC, lgirdwood requested changes
Can you also do this for sof-v4.2 - I guess @xiulipan will move CI over to v4.2 after the Chinese New year at some point so we should be ready for this and for upstreaming.

2020-01-17 14:41 UTC, lgirdwood commented on include/hw/adsp/imx8.h
> +/* Baytrail, Cherrytrail and Braswell */
comments for imx ?

2020-01-17 14:41 UTC, lgirdwood commented on target/xtensa/core-imx8.c
> + * Copyright (c) 2015, Intel Corporation.
copyright NXP ?

2020-01-17 14:41 UTC, lgirdwood commented
@dianacretu please also add what, why and how comments to commit messages and PR descriptions.

2020-02-04 11:24 UTC, lgirdwood reviewed
@dianacretu any update on using the sof 4.2 branch, will be moving docker and CI over to this soon so it's best target for development.

2020-02-15 15:30 UTC, lgirdwood reviewed
@dianacretu are things fully working now ?

2020-02-17 12:30 UTC, dianacretu commented
@lgirdwood booting works fine, thanks for review. Will rebase on sof 4.2 branch with your comments addressed.

2020-02-17 14:26 UTC, lgirdwood commented
@dianacretu ok, great - good to know its all booting now :)

2020-02-20 11:47 UTC, dianacretu commented
Work done. Another pull request was created: https://github.com/thesofproject/qemu/pull/30

2020-02-20 11:47 UTC, closed without merging